### PR TITLE
Review cmake prototypes

### PR DESCRIPTION
**Pull request by Necktschnagge**

### CODE REVIEW

**Comment by Necktschnagge** [comment]
Is this already in README? @r0ost3r 

I guess this is just an old branch that can be deleted.
Can you check?

**Comment by r0ost3r** [comment]
this may be discarded

**Review by r0ost3r — CHANGES_REQUESTED** [review]
This may be discarded.

**Comment by Necktschnagge** [comment]
Closed as @r0ost3r check this and rated it as obsolete.

**Pull request closed without merging**
