### PR TITLE
Single-threaded Tobor Model classes + Solver (without performance optimization)

### PR DESCRIPTION
**Pull request by Necktschnagge**
This is to provide a first version of a ricochet robots solver
* running on single thread
* calculating all optimal solutions

### CODE REVIEW

**Comment by Necktschnagge** [comment]
if possible wait for #14 to be merged

**Comment by Necktschnagge** [comment]
please split the engine.h into two files: 
* model.h for all data model stuff
* engine.h for algorithmic features

**Comment by Necktschnagge** [comment]
CI jobs for windows do not terminate. They get stuck in testing. Probably a performance issue.

Temporarily disabled CI Testing Windows.

**Comment by Necktschnagge** [comment]
TODOs:
* `class move_one_piece_calculator` should be renamed into _*engine_ 
* It should be augmented by some additional features to deal with game states, moves, add a move to a state to get into a next state. some arithmetic-like semtantics might be nice.
* It should provide the engine needed for interactive mode
* we need path classes, for color-agnostic moves and colorful moves
* we need path congruence classes
* We need shrink methods for search space _(There is no strong need for it, but it is a kind of nice enhancement)_

**Comment by Necktschnagge** [comment]
@r0ost3r Mach mal bitte dein Review.

Wenn nichts schlimmes mehr gefunden wird, will ich das so in main mergen.

Falls kleinere Verbesserungen gewünscht sind, machen wir ne Liste, die dann mit einem anderen PullRequest bearbeitet wird.

**Review by r0ost3r — APPROVED** [review]

**Pull request merged**
