### PR TITLE
README and minor other things

### PR DESCRIPTION
**Pull request by Necktschnagge**

### CODE REVIEW

**Comment by Necktschnagge** [comment]
@r0ost3r Do you think this README is sufficient for new developers to know what to do?
Or should I add something?

**Comment by r0ost3r** [comment]
hahn ist zufrieden damit

**Review by r0ost3r — COMMENTED** [review]
hahn ist zufrieden damit

**Review by r0ost3r — APPROVED** [review]

**Comment by r0ost3r** [comment]
@Necktschnagge Mäh?

**Comment by r0ost3r** [comment]
wieso 'cd script' in *-clean-init.* @Necktschnagge ?

**Comment by Necktschnagge** [comment]
> wieso 'cd script' in _-clean-init._ @Necktschnagge ?

Ähm gute Frage, ich gucke mal..

**Comment by r0ost3r** [comment]
mäh! macht sinn. alles gut. kikeriki.

**Comment by Necktschnagge** [comment]
Actually pushd and popd would be more robust solution.
But anyway the scripts should not be executed from another directory.

**Pull request merged**
